FROM python:3.9.1-alpine3.12

RUN mkdir /usr/src/translate_cli

WORKDIR /usr/src/translate_cli

COPY . /usr/src/translate_cli

RUN apk update \
  && apk add --virtual build-deps gcc python3-dev musl-dev \
  && apk add --no-cache mariadb-dev \
  && apk add jpeg-dev zlib-dev freetype-dev lcms2-dev \
  openjpeg-dev tiff-dev tk-dev tcl-dev \
  && apk add libffi-dev py-cffi \
  && apk add gettext \
  && pip install --upgrade pip \
  && pip install -r requirements/dev.txt
