""" Languages list. """

languages_dict = {
    'Afrikaans': 'af',
    'Kirghiz': 'ky',
    'Albanian': 'sq',
    'Korean': 'ko',
    'Arabic': 'ar',
    'Kurdish': 'ku',
    'Armenian': 'hy',
    'Lao': 'lo',
    'Azerbaijani': 'az',
    'Latvian': 'lv',
    'Bashkir': 'ba',
    'Lithuanian': 'lt',
    'Basque': 'eu',
    'Malay': 'ms',
    'Belarusian': 'be',
    'Malayalam': 'ml',
    'Bengali': 'bn',
    'Maltese': 'mt',
    'Bulgarian': 'bg',
    'Marathi': 'mr',
    'Burmese': 'my',
    'Mongolian': 'mn',
    'Catalan': 'ca',
    'Nepali': 'ne',
    'Central Khmer': 'km',
    'Norwegian Bokmål': 'nb',
    'Chinese (Simplified)': 'zh',
    'Norwegian Nynorsk': 'nn',
    'Chinese (Traditional)': 'zh-TW',
    'Punjabi': 'pa',
    'Chuvash': 'cv',
    'Punjabi (Shahmukhi script, Pakistan)': 'pa-PK',
    'Croatian': 'hr',
    'Persian': 'fa',
    'Czech': 'cs',
    'Polish': 'pl',
    'Danish': 'da',
    'Portuguese': 'pt',
    'Dutch': 'nl',
    'Pushto': 'ps',
    'English': 'en',
    'Romanian': 'ro',
    'Esperanto': 'eo',
    'Russian': 'ru',
    'Estonian': 'et',
    'Serbian': 'sr',
    'Finnish': 'fi',
    'Sinhala': 'si',
    'French': 'fr',
    'Slovakian': 'sk',
    'Georgian': 'ka',
    'Slovenian': 'sl',
    'German': 'de',
    'Somali': 'so',
    'Greek': 'el',
    'Spanish': 'es',
    'Gujarati': 'gu',
    'Swedish': 'sv',
    'Haitian': 'ht',
    'Tagalog': 'tl',
    'Hebrew': 'he',
    'Tamil': 'ta',
    'Hindi': 'hi',
    'Telugu': 'te',
    'Hungarian': 'hu',
    'Thai': 'th',
    'Icelandic': 'is',
    'Turkish': 'tr',
    'Irish': 'ga',
    'Ukrainian': 'uk',
    'Italian': 'it',
    'Urdu': 'ur',
    'Japanese': 'ja',
    'Vietnamese': 'vi',
    'Kazakh': 'kk',
    'Welsh': 'cy'
}

languages_list = [
    'af', 'ky', 'sq', 'ko', 'ar', 'ku', 'hy', 'lo', 'az', 'lv', 'ba', 'lt',
    'eu', 'ms', 'be', 'ml', 'bn', 'mt', 'bg', 'mr', 'my', 'mn', 'ca', 'ne',
    'km', 'nb', 'zh', 'nn', 'zh-TW', 'pa', 'cv', 'pa-PK', 'hr', 'fa', 'cs',
    'pl', 'da', 'pt', 'nl', 'ps', 'en', 'ro', 'eo', 'ru', 'et', 'sr', 'fi',
    'si', 'fr', 'sk', 'ka', 'sl', 'de', 'so', 'el', 'es', 'gu', 'sv', 'ht',
    'tl', 'he', 'ta', 'hi', 'te', 'hu', 'th', 'is', 'tr', 'ga', 'uk', 'it',
    'ur', 'ja', 'vi', 'kk', 'cy'
]

languages_tuple = [
    ('Afrikaans', 'af'), ('Kirghiz', 'ky'), ('Albanian', 'sq'),
    ('Korean', 'ko'), ('Arabic', 'ar'), ('Kurdish', 'ku'),
    ('Armenian', 'hy'), ('Lao', 'lo'), ('Azerbaijani', 'az'),
    ('Latvian', 'lv'), ('Bashkir', 'ba'), ('Lithuanian', 'lt'),
    ('Basque', 'eu'), ('Malay', 'ms'), ('Belarusian', 'be'),
    ('Malayalam', 'ml'), ('Bengali', 'bn'), ('Maltese', 'mt'),
    ('Bulgarian', 'bg'), ('Marathi', 'mr'), ('Burmese', 'my'),
    ('Mongolian', 'mn'), ('Catalan', 'ca'), ('Nepali', 'ne'),
    ('Central Khmer', 'km'), ('Norwegian Bokmål', 'nb'),
    ('Chinese (Simplified)', 'zh'), ('Norwegian Nynorsk', 'nn'),
    ('Chinese (Traditional)', 'zh-TW'), ('Punjabi', 'pa'),
    ('Chuvash', 'cv'), ('Punjabi (Shahmukhi script, Pakistan)', 'pa-PK'),
    ('Croatian', 'hr'), ('Persian', 'fa'), ('Czech', 'cs'),
    ('Polish', 'pl'), ('Danish', 'da'), ('Portuguese', 'pt'),
    ('Dutch', 'nl'), ('Pushto', 'ps'), ('English', 'en'),
    ('Romanian', 'ro'), ('Esperanto', 'eo'), ('Russian', 'ru'),
    ('Estonian', 'et'), ('Serbian', 'sr'), ('Finnish', 'fi'),
    ('Sinhala', 'si'), ('French', 'fr'), ('Slovakian', 'sk'),
    ('Georgian', 'ka'), ('Slovenian', 'sl'), ('German', 'de'),
    ('Somali', 'so'), ('Greek', 'el'), ('Spanish', 'es'),
    ('Gujarati', 'gu'), ('Swedish', 'sv'), ('Haitian', 'ht'),
    ('Tagalog', 'tl'), ('Hebrew', 'he'), ('Tamil', 'ta'),
    ('Hindi', 'hi'), ('Telugu', 'te'), ('Hungarian', 'hu'),
    ('Thai', 'th'), ('Icelandic', 'is'), ('Turkish', 'tr'),
    ('Irish', 'ga'), ('Ukrainian', 'uk'), ('Italian', 'it'),
    ('Urdu', 'ur'), ('Japanese', 'ja'), ('Vietnamese', 'vi'),
    ('Kazakh', 'kk'), ('Welsh', 'cy')
]
